#!/bin/sh
# Compiles the Vulkan shaders to SPIR-V and writes src/ov_vk_spv.h.
#
# Run on a build host with glslangValidator; the generated header is committed,
# so building the layer needs no shader compiler.
#
#   ./tools/gen_shaders.sh [path/to/glslangValidator]
set -e

here=$(dirname "$0")
root=$(cd "$here/.." && pwd)
glslang=${1:-$(command -v glslangValidator || true)}
[ -n "$glslang" ] || { echo "glslangValidator not found; pass its path" >&2; exit 1; }

out=$root/src/ov_vk_spv.h
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

{
    echo "/* Generated by tools/gen_shaders.sh -- do not edit."
    echo " *"
    echo " * SPIR-V for shaders/overlay.vert and shaders/overlay.frag."
    echo " */"
    echo "#ifndef OV_VK_SPV_H_INCLUDED"
    echo "#define OV_VK_SPV_H_INCLUDED"
    echo
    echo "#include <stdint.h>"
} > "$out"

for stage in vert frag; do
    "$glslang" -V "$root/shaders/overlay.$stage" -o "$tmp/$stage.spv" > /dev/null
    words=$(od -An -tu4 -v "$tmp/$stage.spv" | tr -s ' ' '\n' | grep -c .)
    {
        echo
        echo "static const uint32_t ov_vk_${stage}_spv[$words] = {"
        od -An -tx4 -v "$tmp/$stage.spv" | tr -s ' ' '\n' | grep . |
            sed 's/^/0x/; s/$/,/' | paste -d' ' - - - - - - |
            sed 's/^/    /; s/[[:space:]]*$//'
        echo "};"
    } >> "$out"
done

echo >> "$out"
echo "#endif /* OV_VK_SPV_H_INCLUDED */" >> "$out"
echo "wrote $out"
