/* Generated by tools/gen_atlas.py -- do not edit.
 *
 * Font: DejaVuSans-Bold.ttf @ 48px, icons drawn procedurally.
 */
#ifndef OV_ATLAS_H_INCLUDED
#define OV_ATLAS_H_INCLUDED

#define OV_ATLAS_W 1024
#define OV_ATLAS_H 196
/* Cap height of the digits, in atlas pixels: text is scaled from this. */
#define OV_ATLAS_CAP 37

typedef struct {
    short x, y, w, h;   /* cell in the atlas, in pixels */
    float advance;      /* pen advance for text glyphs, in atlas pixels */
    short top;          /* rows below the ascender line where the cell starts */
} ov_glyph;

enum {
    OV_G_ICON_SPEAKER = 95,
    OV_G_ICON_SUN = 96,
    OV_G_ICON_BOLT = 97,
    OV_G_ICON_WIFI = 98,
    OV_G_ICON_BLUETOOTH = 99,
    OV_G_COUNT = 100
};

extern const ov_glyph ov_atlas_glyphs[OV_G_COUNT];

/* Printable ASCII, 0x20..0x7e, in order. */
#define OV_ASCII_FIRST 0x20
#define OV_ASCII_LAST  0x7e

extern const unsigned char ov_atlas_ascii[OV_ASCII_LAST - OV_ASCII_FIRST + 1];

/* Glyph index for a character, or the one for '?' when out of range.  A
 * function, not a macro: call sites pass expressions with side effects and a
 * macro would evaluate them more than once. */
static inline int ov_glyph_for(int c)
{
    if (c < OV_ASCII_FIRST || c > OV_ASCII_LAST)
        c = '?';
    return ov_atlas_ascii[c - OV_ASCII_FIRST];
}

#define OV_GLYPH_FOR(c) ov_glyph_for(c)
#define OV_G_D0      ov_glyph_for('0')
#define OV_G_PERCENT ov_glyph_for('%')
#define OV_G_SPACE   ov_glyph_for(' ')

extern const unsigned char ov_atlas_pixels[OV_ATLAS_W * OV_ATLAS_H];

#endif /* OV_ATLAS_H_INCLUDED */
